version: '3'
services:
  app1:
    image: clusterapp
    ports:
      - "8081:8080"
  app2:
    image: clusterapp
    ports:
      - "8082:8080"
  app3:
    image: clusterapp
    ports:
      - "8083:8080"
  app4:
    image: clusterapp
    ports:
      - "8084:8080"
  app5:
    image: clusterapp
    ports:
      - "8085:8080"
  app6:
    image: clusterapp
    ports:
      - "8086:8080"

  nginx:
    image: nginx:latest
    ports:
      - "8888:8888"  # 호스트의 8888 포트를 컨테이너의 8888 포트와 매핑
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3
      - app4
      - app5
      - app6