# cluster app 접속 외부 노춡x, 오직 nginx를 통해서만
version: '3'
services:
  app1:
    image: clusterapp:2.0
    expose:
      - "8080"
    restart: always  # 컨테이너가 중지되면 항상 다시 시작
    
  app2:
    image: clusterapp:2.0
    expose:
      - "8080"
    restart: always  # 컨테이너가 중지되면 항상 다시 시작
    
  app3:
    image: clusterapp:1.0
    expose:
      - "8080"
    restart: always  # 컨테이너가 중지되면 항상 다시 시작
    
  app4:
    image: clusterapp:1.0
    expose:
      - "8080"
    restart: always  # 컨테이너가 중지되면 항상 다시 시작
    
  app5:
    image: clusterapp:2.0
    expose:
      - "8080"
    restart: always  # 컨테이너가 중지되면 항상 다시 시작
    
  app6:
    image: clusterapp:1.0
    expose:
      - "8080"
    restart: always  # 컨테이너가 중지되면 항상 다시 시작

  nginx:
    image: nginx:latest
    ports:
      - "8888:8888"  # 호스트의 8888 포트를 컨테이너의 8888 포트와 매핑
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3
      - app4
      - app5
      - app6
    restart: always